Global:
  model_name: license_plate_japan_rec
  debug: false
  use_gpu: true
  epoch_num: 300
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/license_plate_japan_rec
  save_epoch_step: 10
  eval_batch_step: [0, 500]
  cal_metric_during_train: true
  pretrained_model:
  checkpoints:
  save_inference_dir:
  use_visualdl: false
  infer_img:
  # カスタム辞書を使用（ナンバープレート専用）
  character_dict_path: custom_configs/license_plate_japan/license_plate_dict.txt
  # ナンバープレートは短いので15文字で十分
  max_text_length: &max_text_length 15
  infer_mode: false
  use_space_char: true
  distributed: true
  save_res_path: ./output/rec/predicts_license_plate.txt


Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    # ファインチューニング用に学習率を低めに設定
    learning_rate: 0.0005
    warmup_epoch: 5
  regularizer:
    name: L2
    factor: 3.0e-05


Architecture:
  model_type: rec
  algorithm: SVTR_LCNet
  Transform:
  Backbone:
    name: MobileNetV1Enhance
    scale: 0.5
    last_conv_stride: [1, 2]
    last_pool_type: avg
    last_pool_kernel_size: [2, 2]
  # シンプルなCTCHeadのみを使用（ナンバープレート認識にはこれで十分）
  Head:
    name: CTCHead
    Neck:
      name: svtr
      dims: 64
      depth: 2
      hidden_dims: 120
      use_guide: True
    fc_decay: 0.00001

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc
  ignore_space: False

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/license_plate/
    ext_op_transform_idx: 1
    label_file_list:
    - ./train_data/license_plate/train_list.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    # データ拡張を追加（限られたデータセットでの過学習を防ぐ）
    - RecConAug:
        prob: 0.5
        ext_data_num: 2
        image_shape: [48, 320, 3]
    - RecAug:
    - CTCLabelEncode:
    # ナンバープレート用の画像サイズ（横長）
    - RecResizeImg:
        image_shape: [3, 48, 320]
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    shuffle: true
    batch_size_per_card: 128
    drop_last: true
    num_workers: 4

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/license_plate/
    label_file_list:
    - ./train_data/license_plate/val_list.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - CTCLabelEncode:
    - RecResizeImg:
        image_shape: [3, 48, 320]
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 128
    num_workers: 4
